config/routes.rb
Splitwise::Application.routes.draw do
  resources :users
  resources :sessions
  resources :dashboard, :expenses, :tabs

  match '/login',  to: 'sessions#login',   via: 'get'
  match '/logon',  to: 'sessions#login',   via: 'get'
  match '/create', to: 'sessions#create',  via: 'post'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  

end

app/models/tab.rb
class Tab < ActiveRecord::Base
  belongs_to :users
  has_many :expenses
  has_many :participants

  def this_tabs_expenses
    @this_tabs_expenses ||= this_tabs_expenses!
  end

  def this_tabs_expenses!
    @this_tabs_expenses = Expense.where(tab_id: self.id)
  end

  def this_tabs_users
    @this_tabs_users ||= this_tabs_users!
  end

  def this_tabs_users!
    @this_tabs_users = User.joins('INNER JOIN participants ON participants.user_id = users.id').where(participants: { tab_id: self.id })
  end

  def total_amount
    @total_amount ||= total_amount!
  end

  def total_amount!
    @total_amount = 0
    this_tabs_expenses!.each do |e|
      @total_amount += e.amount
    end
    return @total_amount
  end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  include TabsHelper
  before_action :require_login
  before_action :set_tab, only: [:show, :edit, :update, :destroy]
  before_action :all_users, only: [:new, :edit]
  before_action :exclude_non_owner, only: [:edit, :update, :show, :destroy]

  def index
    redirect_to({controller: :dashboard})
  end

  def new
    @tab = Tab.new
  end

  def create
    @tab = Tab.new(params_to_save)
    success = @tab.save ? true : false
    save_tab(success)
  end

  def update
    success = @tab.update(params_to_save) ? true : false
    save_tab(success, 'updated')
  end

  def edit
  end

  # DELETE /tabs/1
  # DELETE /tabs/1.json
  def destroy
    @tab.destroy
    respond_to do |format|
      format.html { redirect_to '/dashboard' }
      format.json { head :no_content }
    end
  end

  private
    def set_tab
      @tab = Tab.find(params[:id])
      @expenses = Expense.where(user_id: current_user.id, tab_id: params[:id])
      @total_amt = 0
      @expenses.each do |e|
        @total_amt += e.amount
      end

      @participants = User.joins('INNER JOIN participants ON participants.user_id = users.id').where(participants: { tab_id: @tab.id })
    end

    def all_users
      @all_users = User.all
    end

    def tab_params
      params.require(:tab).permit(C_NAME, C_DESCRIPTION, C_SPLITTERS => [])
    end

    def params_to_save
      tab_params.permit(C_NAME, C_DESCRIPTION).merge(user_id: current_user.id)
    end

    def checkbox_values
      tab_params[C_SPLITTERS]
    end

    def exclude_non_owner
      tab = Tab.find_by_id(params[:id])
      unless tab.user_id == current_user.id
        redirect_to({controller: :dashboard})
      end
    end

    # @param [TrueClass, FalseClass] success Whether the save or update was successful
    # @param [String] notice_status Use to create success message
    def save_tab(success, notice_status = 'created')
      if checkbox_values
        checkbox_values.each do |value|
          already_in_db = Participant.where(tab_id: @tab_id, user_id: value.to_i)
          if already_in_db.count == 0
            participant = Participant.new(tab_id: @tab.id, user_id: value.to_i)
            participant.save
          end
        end
      end

      respond_to do |format|
        if success
          format.html { redirect_to @tab, notice: "Tab was successfully #{notice_status}." }
          format.json { render action: 'show', status: :created, location: @tab }
        else
          format.html { render action: 'new' }
          format.json { render json: @tab.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/tabs_helper.rb
module TabsHelper
  C_NAME        = :name
  C_DESCRIPTION = :description
  C_SPLITTERS   = :splitters
end

app/views/tabs/_form.html.erb
<%= form_for(@tab) do |f| %>
  <% if @tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tab.errors.count, "error") %> Prohibited this expense from being saved:</h2>

      <ul>
      <% @tab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <% if @all_users %>
    <h3>Select users to share the expenses in this tab:</h3>
    <% @all_users.each do |user| %>
      <%= check_box_tag "tab[splitters][]", "#{user.id}" %>
    <% end %>
  <% else %>
    <p>Sorry, there are no users who can share your expenses. Invite some!</p>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tabs/edit.html.erb
<h1>Edit a Tab</h1>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', '/dashboard' %>

app/views/tabs/new.html.erb
<h1>Create a new tab.</h1>
<div>A tab is a collection of expenses that you can split among your friends.</div>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', '/dashboard' %>

app/views/tabs/show.html.erb
<h1>Tab Details</h1>

<p>
  <strong>Tab Name:</strong>
  <%= @tab.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tab.description %>
</p>

<p>
  <strong>Expenses in this tab:</strong>
  <% if @expenses %>
    <ul>
      <% @expenses.each do |expense| %>
        <li><%= expense.name %>: <%= format_dollars(expense.amount) %></li>
      <% end %>
    </ul>
    <div><strong>Total amount:</strong> <%= format_dollars(@total_amt) %></div>
  <% else %>
    <div>You have no expenses in this tab.<div>
  <% end %>
</p>

<p>
  <strong>Users splitting this tab:</strong>
  <% if @participants %>
    <ul>
      <% @participants.each do |participant| %>
        <li><%= participant.fname + ' ' + participant.lname %></li>

      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_tab_path(@tab) %>
<%= link_to 'Delete', @tab, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Dashboard', {controller: :dashboard} %>