config/routes.rb
Splitwise::Application.routes.draw do
  resources :users
  resources :sessions
  resources :dashboard, :expenses, :tabs

  match '/login',  to: 'sessions#login',   via: 'get'
  match '/logon',  to: 'sessions#login',   via: 'get'
  match '/create', to: 'sessions#create',  via: 'post'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  include ExpensesHelper, SessionsHelper
  before_action :require_login
  before_action :get_all_tabs, only: [:show, :update, :edit]
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :exclude_non_owner, only: [:edit, :update, :show, :destroy]

  def index
    redirect_to({controller: :dashboard})
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(params_to_save)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @expense.update(params_to_save)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    def set_expense
      @expense = Expense.find(params[:id])
    end

    def expense_params
      params.require(:expense).permit(C_NAME, C_AMOUNT, C_DESCRIPTION, C_TAB_ID)
    end

    def params_to_save
      expense_params.merge(user_id: current_user.id)
    end

    def exclude_non_owner
      expense = Expense.find_by_id(params[:id])
      unless expense.user_id == current_user.id
        redirect_to({controller: :dashboard})
      end
    end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
  C_USER_ID     = :user_id
  C_NAME        = :name
  C_AMOUNT      = :amount
  C_DESCRIPTION = :description
  C_TAB_ID      = :tab_id

  def tab_select_list_array
    tabs_array = []
    if @tabs
      @tabs.each do |tab|
        tabs_array.push [tab.name, tab.id]
      end
      options_for_select(tabs_array)
    end
  end
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> Prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <% if @tabs %>
    <div class="select-list">
      <%= f.select(:tab_id, tab_select_list_array) %>
    </div>
  <% else %>
    <p>You have to active tabs to which you can add this expense. 
        <%= link_to 'Create a new tab here', new_tab_path %>.</p>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/destroy.html.erb
<h1>Expenses#destroy</h1>
<p>Find me in app/views/expenses/destroy.html.erb</p>

app/views/expenses/edit.html.erb
<h1>Edit an Expense</h1>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', '/dashboard' %>

app/views/expenses/new.html.erb
<h1>Create a new expense.</h1>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', '/dashboard' %>

app/views/expenses/show.html.erb
<h1>Expenses Details</h1>

<p>
  <strong>Expense Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= format_dollars_cents(@expense.amount) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<% if @expense.tab_id %>
  <p>
    <strong>Tab:</strong>
    <%= @expense.tab_id %>
  </p>
<% else %>
  <p><i>TODO: Add handling for no tab_id</i></p>
<% end %>

<%= link_to 'Edit', edit_expense_path(@expense) %>
<%= link_to 'Delete', @expense, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Dashboard', {controller: :dashboard} %>